CODE_TOKENS = [
    # "<|c++|>",
    # "<|c|>",
    # "<|dockerfile|>",
    # "<|go|>",
    # "<|java|>",
    # "<|javascript|>",
    # "<|markdown|>",
    # "<|python|>",
    # "<|typescript|>",
    # "<|rust|>",
    # "<|sql|>",
    # "<|shell|>",

    "<|c++|>",
    "<|go|>",
    "<|sql|>",
    "<|typescript|>",
    "<|c|>",
    "<|java|>",
    "<|python|>",
    "<|shell|>",
    "<|javascript|>",
]
